# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2I0NTMyNDM5NmI2ZDY2NzliODQ1ZGQxYjdmNWNmNDY0ODRhY2Q4M2E2ZTQ1MDVlZjMwMmMyM2UxMjRmN2JiNDQ2MDIyZTdkODNhNjdkZjJlMjJkYmU5NjIxN2QyYTI5OWZkMWJhYzlhNjBlZDBjZmU3NzRiM2MwNTY2YzdiNzQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
